= ocp4-workload-ccnrd-fsi-overlay - Reconfigure CCNR Hands-On Lab for the Beyond 2020 FSI Workshop

== Role overview

* This role enables the Cloud-Native Workshop Dev Track on an OpenShift 4 Cluster. It consists of the following playbooks:
** Playbook: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment.
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Playbook: link:./tasks/workload.yml[workload.yml] - Used to deploy the Cloud-Native Workshop Dev Track and then deploy a Workshop instance
*** Debug task will print out: `workload Tasks completed successfully.`

** Playbook: link:./tasks/post_workload.yml[post_workload.yml] - Used to
 configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Playbook: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to
 delete the workload
*** This role removes the Workshop Instance and Cloud-Native Workshop Dev Track from OCP 4. This role does *not* remove the project - there may be other items in it.
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.
* The variable *ocp_username* is mandatory to assign the workload to the correct OpenShift user.
* A variable *silent=True* can be passed to suppress debug messages.
* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line

=== Deploy a Workload with the `ocp4-workload-ccnrd-fsi-overlay` playbook [Mostly for testing]
                   
----
TARGET_HOST="BASTION_HOST_CHANGE_ME"
OCP_USERNAME="opentlc-mgr"
WORKLOAD="ocp4-workload-ccnrd-fsi-overlay"
GUID="GUIDE_CHANGE_ME"
ACTION="create"

ANSIBLE_SSH_USER="BASTION_USER_CHANGE_ME"
ANSIBLE_SSH_PWD="BASTION_PASSWORD_CHANGE_ME"

NUM_USERS="30"
MODULE_TYPE="m1;m3"

# change dir to agnosticd/ansible path
cd ../../

ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e @./roles/${WORKLOAD}/defaults/main.yml \
    -e"num_users=${NUM_USERS}" \
    -e"module_type=${MODULE_TYPE}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"ACTION=${ACTION}" \
    -e"ansible_user=${ANSIBLE_SSH_USER}" \
    -e"ansible_password=${ANSIBLE_SSH_PWD}" \
    -e"guid=${GUID}"
----

